#ifndef OPEN62541_CONFIG_H
#define OPEN62541_CONFIG_H

#define UA_LOGLEVEL 300
#ifndef UA_ENABLE_AMALGAMATION
    #define UA_ENABLE_AMALGAMATION
#endif
#define UA_ENABLE_METHODCALLS
#define UA_ENABLE_NODEMANAGEMENT
#define UA_ENABLE_SUBSCRIPTIONS
// #define UA_ENABLE_PUBSUB 
// #define UA_ENABLE_PUBSUB_ENCRYPTION 
// #define UA_ENABLE_PUBSUB_FILE_CONFIG 
// #define UA_ENABLE_PUBSUB_ETH_UADP 
// #define UA_ENABLE_PUBSUB_DELTAFRAMES 
// #define UA_ENABLE_PUBSUB_INFORMATIONMODEL 
// #define UA_ENABLE_PUBSUB_INFORMATIONMODEL_METHODS 
#define UA_ENABLE_DA
// #define UA_ENABLE_DIAGNOSTICS 
// #define UA_ENABLE_HISTORIZING 
#define UA_ENABLE_PARSING
// #define UA_ENABLE_EXPERIMENTAL_HISTORIZING 
// #define UA_ENABLE_SUBSCRIPTIONS_EVENTS 
// #define UA_ENABLE_JSON_ENCODING 
// #define UA_ENABLE_PUBSUB_MQTT 
// #define UA_ENABLE_MQTT_TLS 
// #define UA_ENABLE_MQTT_TLS_OPENSSL 
// #define UA_ENABLE_MQTT_TLS_MBEDTLS 
// #define UA_ENABLE_ENCRYPTION_MBEDTLS 
// #define UA_ENABLE_TPM2_SECURITY 
// #define UA_ENABLE_ENCRYPTION_OPENSSL 
// #define UA_ENABLE_ENCRYPTION_LIBRESSL 
#if defined(UA_ENABLE_ENCRYPTION_MBEDTLS) || defined(UA_ENABLE_ENCRYPTION_OPENSSL) || defined(UA_ENABLE_ENCRYPTION_LIBRESSL)
    #define UA_ENABLE_ENCRYPTION
#endif
// #define UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS 

/* Multithreading */
// #define UA_ENABLE_IMMUTABLE_NODES 
#define UA_MULTITHREADING 0

/* Advanced Options */
#define UA_ENABLE_STATUSCODE_DESCRIPTIONS
#define UA_ENABLE_TYPEDESCRIPTION
#define UA_ENABLE_NODESET_COMPILER_DESCRIPTIONS
// #define UA_ENABLE_DETERMINISTIC_RNG 
// #define UA_ENABLE_DISCOVERY 
// #define UA_ENABLE_DISCOVERY_MULTICAST 
// #define UA_ENABLE_WEBSOCKET_SERVER 
// #define UA_ENABLE_QUERY 
// #define UA_ENABLE_MALLOC_SINGLETON 
#define UA_ENABLE_DISCOVERY_SEMAPHORE
// #define UA_ENABLE_UNIT_TEST_FAILURE_HOOKS 
// #define UA_ENABLE_VALGRIND_INTERACTIVE 
#define UA_VALGRIND_INTERACTIVE_INTERVAL 1000
// #define UA_GENERATED_NAMESPACE_ZERO 
// #define UA_GENERATED_NAMESPACE_ZERO_FULL 
// #define UA_ENABLE_PUBSUB_MONITORING 
// #define UA_ENABLE_PUBSUB_BUFMALLOC 

// #define UA_PACK_DEBIAN 

/* Options for Debugging */
#define UA_DEBUG
// #define UA_DEBUG_DUMP_PKGS 
// #define UA_DEBUG_FILE_LINE_INFO 
/**
 * Function Export
 * ---------------
 * On Win32: Define ``UA_DYNAMIC_LINKING`` and ``UA_DYNAMIC_LINKING_EXPORT`` in
 * order to export symbols for a DLL. Define ``UA_DYNAMIC_LINKING`` only to
 * import symbols from a DLL.*/
// #define UA_DYNAMIC_LINKING */

#endif // !OPEN62541_CONFIG_H